/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Tom Fynes",
  "tagline": "Software Engineer",
  "favicon": "img/TF_logo.png",
  "url": "https://tom-fynes.github.io",
  "baseUrl": "/",
  "organizationName": "Tom-Fynes",
  "projectName": "https://github.com/tom-fynes.github.io",
  "trailingSlash": false,
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "plugins": [
    null,
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "Git-101",
        "path": "git_101",
        "routeBasePath": "git_101",
        "sidebarPath": "./sidebars.js"
      }
    ]
  ],
  "themes": [
    "@docusaurus/theme-mermaid"
  ],
  "markdown": {
    "mermaid": true,
    "format": "mdx",
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.js",
          "routeBasePath": "docs/",
          "breadcrumbs": true,
          "showLastUpdateAuthor": true,
          "include": [
            "**/*.md",
            "**/*.mdx"
          ],
          "exclude": [
            "**/_*.{js,jsx,ts,tsx,md,mdx}",
            "**/_*/**",
            "**/*.test.{js,jsx,ts,tsx}",
            "**/__tests__/**"
          ]
        },
        "pages": {
          "path": "src/pages",
          "routeBasePath": "",
          "include": [
            "**/*.{js,jsx,ts,tsx,md,mdx}"
          ],
          "exclude": [
            "**/_*.{js,jsx,ts,tsx,md,mdx}",
            "**/_*/**",
            "**/*.test.{js,jsx,ts,tsx}",
            "**/__tests__/**"
          ],
          "mdxPageComponent": "@theme/MDXPage",
          "rehypePlugins": [],
          "beforeDefaultRemarkPlugins": [],
          "beforeDefaultRehypePlugins": []
        },
        "blog": {
          "showReadingTime": true,
          "blogSidebarTitle": "Recent Posts",
          "postsPerPage": 10,
          "feedOptions": {
            "type": [
              "rss",
              "atom"
            ],
            "xslt": true
          },
          "onInlineTags": "warn",
          "onInlineAuthors": "warn",
          "onUntruncatedBlogPosts": "warn"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/TF_logo.png",
    "navbar": {
      "title": "Tom F",
      "logo": {
        "alt": "My Site Logo",
        "src": "img/TF_logo.png"
      },
      "items": [
        {
          "to": "/blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "label": "Courses",
          "position": "left",
          "type": "dropdown",
          "items": [
            {
              "label": "SQL 101",
              "to": "/docs/intro"
            },
            {
              "label": "Git 101",
              "to": "/git_101/intro"
            }
          ]
        },
        {
          "label": "Projects",
          "position": "left",
          "type": "dropdown",
          "items": [
            {
              "label": "VS Code Theme",
              "href": "https://github.com/Tom-Fynes/nebula-nights"
            }
          ]
        },
        {
          "label": "Resources",
          "position": "left",
          "type": "dropdown",
          "items": [
            {
              "label": "Beginner's Data Toolkit",
              "to": "https://tfynes.gumroad.com/l/phlyc",
              "description": "A collection of notebooks for beginners"
            },
            {
              "label": "Git Cheat Sheet",
              "href": "/downloads/cheatsheet.jpg",
              "target": "_blank",
              "rel": "noopener noreferrer"
            },
            {
              "label": "SQL Cheat Sheet",
              "href": "/downloads/sql_cheatsheet.jpg",
              "target": "_blank",
              "rel": "noopener noreferrer"
            }
          ]
        },
        {
          "to": "skills",
          "label": "Skills",
          "position": "left"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "light",
      "links": [
        {
          "title": "Courses",
          "items": [
            {
              "label": "SQL 101",
              "to": "/docs/intro",
              "description": "Learn the basics of SQL"
            },
            {
              "label": "Git 101",
              "to": "/git_101/intro",
              "description": "Learn the basics of Git"
            }
          ]
        },
        {
          "title": "Socials",
          "items": [
            {
              "label": "GitHub",
              "href": "https://www.github.com/Tom-Fynes"
            },
            {
              "label": "Stack Overflow",
              "href": "https://www.stackoverflow.com/users/7031452/tom"
            },
            {
              "label": "LinkedIn",
              "href": "https://www.linkedin.com/in/thomas-f-b00607163/"
            }
          ]
        },
        {
          "title": "Contact",
          "items": [
            {
              "label": "tf.dev@icloud.com",
              "to": "mailto:tf.dev@icloud.com"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 Tom Fynes."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "mermaid": {
      "theme": {
        "dark": "dark",
        "light": "default"
      },
      "options": {}
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
